---
- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present
  become: yes

- name: Add sbt signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    state: present
  become: yes

- name: Add sbt repository
  apt_repository:
    repo: deb https://dl.bintray.com/sbt/debian /
    state: present
    filename: sbt
  become: yes

- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install sbt
  apt:
    name: sbt
    state: present
  become: yes
