---
- name: Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Mac
  import_tasks: mac.yml
  when: ansible_distribution == 'MacOSX'
