---
- name: Install curl
  apt:
    name: curl
    state: present
  become: yes

- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Install zsh
  apt:
    name: zsh
    state: present
  become: yes

- name: Change default shell to zsh
  user:
    name: '{{ ansible_user }}'
    shell: /bin/zsh
  become: yes

- name: Install neovim
  apt:
    name: neovim
    state: present
  become: yes

- name: Install FiraCode font
  apt:
    name: fonts-firacode
    state: present
  become: yes

- name: Install exfat-fuse
  apt:
    name: exfat-fuse
    state: present
  become: yes

- name: Install exfat-utils
  apt:
    name: exfat-utils
    state: present
  become: yes
