---
- name: Add go repository
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present
  become: yes

- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install go
  apt:
    name: golang-go
    state: present
  become: yes
