---
- name: Install DataGrip
  snap:
    name: datagrip
    classic: yes
    state: present
  become: yes

- name: Install CLion
  snap:
    name: clion
    classic: yes
    state: present
  become: yes

- name: Install GoLand
  snap:
    name: goland
    classic: yes
    state: present
  become: yes

- name: Install VSCode
  snap:
    name: code
    classic: yes
    state: present
  become: yes

- name: Install guake
  apt:
    name: guake
    state: present
  become: yes

- name: Install Spotify
  snap:
    name: spotify
    state: present
  become: yes

- name: Install Slack
  snap:
    name: slack
    classic: yes
    state: present
  become: yes

- name: Install VLC
  snap:
    name: vlc
    state: present
  become: yes

- name: Install ripgrep
  apt:
    name: ripgrep
    state: present
  become: yes

- name: Install Insomnia
  snap:
    name: insomnia
    state: present
  become: yes

- name: Install Heroku
  snap:
    name: heroku
    state: present
    classic: yes
  become: yes
