---
- name: Add docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
    update_cache: true
  become: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
  become: yes

- name: Add docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: yes
